import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  containerMain: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    paddingTop: 60,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '100%',
    justifyContent: 'center',
  },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 30, // 50% do tamanho para deixá-la redonda
    marginRight: 10,
  },
  avatarMain: {
    width: 70,
    height: 70,
    borderRadius: 50, // 50% do tamanho para deixá-la redonda
    marginRight: 10,
  },
  logo: {
    width: 230,
    height: 230,
    borderRadius: 115,
    marginBottom: 20,
  },
  title: {
    fontSize: 62,
    fontFamily: 'Lobster-Regular',
    fontWeight: '400',
    color: '#FFFFFF',
    // marginBottom: 20,
    marginRight: 20,
  },
  subtitle: {
    fontSize: 20,
    fontFamily:'Roboto',
    fontWeight:500,
    color: '#E8E8E8',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 60,
  },
  helloUser: {
    fontSize: 25,
    fontFamily:'Roboto',
    fontWeight:700,
    color: '#2F80ED',
    textAlign: 'center',
    marginLeft: -20,
    marginRight: 20,
  },
  button: {
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 10,
    width: 280,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '500',
  },
  text: {
    fontSize: 20,
    fontWeight: '500',
    color: '#2F80ED',
  },
  linkText: {
    fontSize: 16,
    color: '#007AFF',
    marginTop: 20,
    textDecorationLine: 'none',
  },
  inputContainer: {
    boxShadow: '0px 0px 10px 0px rgba(0, 0, 0, 0.7)',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    width: 300,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 10,
  },
  
  backButton: {
    position: 'absolute',
    top: 40,
    left: -15,
  },
  backButtonMain: {
    position: 'absolute',
    top: 40,
    left: 15,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    marginBottom: 20,
  },
   content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    paddingBottom: 60,
  },
  searchInput: {
    width: '100%',
    height: 40,
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 15,
    marginBottom: 20,
    color: '#000',
  },
  optionButton: {
    backgroundColor: '#87CEEB',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginVertical: 5,
    width: '100%',
    alignItems: 'center',
  },
  bottomNav: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255, 0.5)',
    bottom: 0,
    left: 0,
    right: 0,
  },
  activeIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF0000',
    marginTop: 2,
    alignSelf: 'center',
  },
});

export default globalStyles;